### ISSUE TITLE
How should projectors handle unexpectedly missing projections?

### ISSUE THREAD

**Issue by IharBury** [dennisdoomen/LiquidProjections#45]
Currently projectors configure event maps to always create missing projections when handling events as update. That allows to handle events which introduce new projections as update events. However that also affects the situation when a projection which should already be created is somehow missing. Some projections can have properties which should always be set to some non-null value. It may not be possible to update such projections without initializing their required properties first.

**Comment by dennisdoomen** [comment]
Considering our recent experiences with all kinds of side-effects caused by automatically created projections, it is my opinion that it should never automatically create projections.

**Comment by IharBury** [comment]
Started working on this.
