### ISSUE TITLE
Handling lookup tables in event maps

### ISSUE THREAD

**Issue by IharBury** [dennisdoomen/LiquidProjections#46]
Currently projectors configure event maps to handle updates and deletes for the projection itself. However, projections can also use lookup tables. We should probably make it possible to reuse the configuration code for lookup event maps. For example, we could create extension methods like `IEventMapBuilder.SetupRavenDbHandlers`, `IEventMapBuilder.SetupNHibernateHandlers`, etc.

**Comment by dennisdoomen** [comment]
Let's re-evaluate this when we've seen some real-life implementations that we can extract a pattern from.

**Comment by IharBury** [comment]
Resolved by #55
