### ISSUE TITLE
DateTime.Now for LruProjectionCache

### ISSUE THREAD

**Issue by IharBury** [dennisdoomen/LiquidProjections#49]
`() => DateTime.Now` is passed as the `getNow` parameter to the `LruProjectionCache` in specs and in the example. That will not work properly when the local time zone is changed due to light-saving. We should use `() => DateTime.UtcNow` instead. And maybe even change the parameter name to make it clear that we expect UTC time.

**Comment by dennisdoomen** [comment]
Agreed.
