### ISSUE TITLE
Add retry support

### ISSUE THREAD

**Issue by dennisdoomen** [dennisdoomen/LiquidProjections#83]
A projector such as the `NHibernateProjector` projects a page of transactions in batches of a configured size. Each batch is executed in a database transaction. If any but the first batch fails, the projector needs to communicate to the caller that is has partially projected the transactions, so that the caller understands it must only send the unprocessed transactions. This puts a lot of complexity on the calling code. Instead, offer a way to retry projections in NHibernate and RavenDB.

**Comment by corvansteijn** [comment]
pr #84 implements this. Does it meet your expectations? If so, I can also implement it for the RavenDB and regular projectors
